In [2]:
import pandas as pd
import pandera as pa

In [35]:
valores_ausentes = ['**','###!','####','***','****','NULL'] #limpeza dos dados na leitura
df = pd.read_csv('ocorrencia.csv', sep=";", parse_dates=["ocorrencia_dia"], dayfirst=True, na_values=valores_ausentes)
df.head(10)

,codigo_ocorrencia,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,52242,INCIDENTE,PORTO ALEGRE,RS,BRASIL,SBPA,2012-01-05,20:27:00,0.0
1,45331,ACIDENTE,GUARULHOS,SP,BRASIL,SBGR,2012-01-06,13:44:00,3.0
2,45333,ACIDENTE,VIAMÃO,RS,BRASIL,NaN,2012-01-06,13:00:00,0.0
3,45401,ACIDENTE,SÃO SEBASTIÃO,SP,BRASIL,NaN,2012-01-06,17:00:00,0.0
4,45407,ACIDENTE,SÃO SEPÉ,RS,BRASIL,NaN,2012-01-06,16:30:00,0.0
5,52243,INCIDENTE,UBATUBA,SP,BRASIL,NaN,2012-01-06,14:30:00,0.0
6,50713,INCIDENTE GRAVE,CAMPINAS,SP,BRASIL,SDAI,2012-01-07,18:15:00,0.0
7,45334,INCIDENTE,BELÉM,PA,BRASIL,SBBE,2012-01-08,19:12:00,0.0
8,45391,ACIDENTE,CONCEIÇÃO DAS ALAGOAS,MG,BRASIL,NaN,2012-01-08,16:00:00,0.0
9,52244,INCIDENTE,UBERLÂNDIA,MG,BRASIL,SBUL,2012-01-08,22:13:00,0.0

In [5]:
schema = pa.DataFrameSchema(
    columns = { 
        "codigo_ocorrencia": pa.Column(pa.Int),
        "ocorrencia_classificacao": pa.Column(pa.Object),
        "ocorrencia_cidade": pa.Column(pa.Object),
        "ocorrencia_uf": pa.Column(pa.Object, pa.Check.str_length(2,2), nullable=True),
        "ocorrencia_aerodromo": pa.Column(pa.Object, nullable=True),
        "ocorrencia_dia": pa.Column(pa.DateTime, nullable=True),
        "ocorrencia_hora": pa.Column(pa.String, nullable=True),
        "total_recomendacoes": pa.Column(pa.Float, nullable=True)
    }
)

In [6]:
schema.validate(df)

,codigo_ocorrencia,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,52242,INCIDENTE,PORTO ALEGRE,RS,BRASIL,SBPA,2012-01-05,20:27:00,0.0
1,45331,ACIDENTE,GUARULHOS,SP,BRASIL,SBGR,2012-01-06,13:44:00,3.0
2,45333,ACIDENTE,VIAMÃO,RS,BRASIL,NaN,2012-01-06,13:00:00,0.0
3,45401,ACIDENTE,SÃO SEBASTIÃO,SP,BRASIL,NaN,2012-01-06,17:00:00,0.0
4,45407,ACIDENTE,SÃO SEPÉ,RS,BRASIL,NaN,2012-01-06,16:30:00,0.0
...,...,...,...,...,...,...,...,...,...
5158,80458,ACIDENTE,JATAÍ,GO,BRASIL,NaN,2021-12-30,20:30:00,0.0
5159,80452,ACIDENTE,MARACAÍ,SP,BRASIL,NaN,2021-12-31,09:30:00,0.0
5160,80457,INCIDENTE GRAVE,NOVO HAMBURGO,RS,BRASIL,SSNH,2021-12-31,11:59:00,0.0
5161,80460,INCIDENTE,CURITIBA,PR,BRASIL,SBBI,2021-12-31,15:12:00,0.0
5162,80467,INCIDENTE,PETROLINA,PE,BRASIL,SBPL,2021-12-31,20:30:00,0.0

In [48]:
df.dtypes

codigo_ocorrencia                    int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_pais                     object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                float64
dtype: object

In [50]:
#consultando por indices
df.iloc[13:16]

,codigo_ocorrencia,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
13,45408,ACIDENTE,ELDORADO,SP,BRASIL,NaN,2012-01-11,13:45:00,1.0
14,45447,INCIDENTE,RIO BRANCO,AC,BRASIL,NaN,2012-01-13,18:15:00,0.0
15,45409,ACIDENTE,CÁCERES,MT,BRASIL,NaN,2012-01-14,10:00:00,0.0

In [52]:
#trazendo dados de uma coluna
df['ocorrencia_hora']

0       20:27:00
1       13:44:00
2       13:00:00
3       17:00:00
4       16:30:00
          ...
5158    20:30:00
5159    09:30:00
5160    11:59:00
5161    15:12:00
5162    20:30:00
Name: ocorrencia_hora, Length: 5163, dtype: object

In [53]:
df.isna().sum()

codigo_ocorrencia              0
ocorrencia_classificacao       0
ocorrencia_cidade              0
ocorrencia_uf                  2
ocorrencia_pais                0
ocorrencia_aerodromo        1904
ocorrencia_dia                 2
ocorrencia_hora                1
total_recomendacoes            3
dtype: int64

In [54]:
#localizando valores nulos em uma coluna específica
df.loc[df.ocorrencia_uf.isnull()]

,codigo_ocorrencia,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
1099,49474,ACIDENTE,ÁGUAS INTERNACIONAIS**BRASIL,NaN,02/09/2013,NaN,2018-05-10,0,NaN
4726,79956,ACIDENTE,NÃO IDENTIFICADA**BRASIL,NaN,26/02/2021,NaN,NaT,0,NaN

In [57]:
#localizando valores nulos em uma coluna específica
filtro = df.ocorrencia_aerodromo.isnull()
df.loc[filtro]

,codigo_ocorrencia,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2,45333,ACIDENTE,VIAMÃO,RS,BRASIL,NaN,2012-01-06,13:00:00,0.0
3,45401,ACIDENTE,SÃO SEBASTIÃO,SP,BRASIL,NaN,2012-01-06,17:00:00,0.0
4,45407,ACIDENTE,SÃO SEPÉ,RS,BRASIL,NaN,2012-01-06,16:30:00,0.0
5,52243,INCIDENTE,UBATUBA,SP,BRASIL,NaN,2012-01-06,14:30:00,0.0
8,45391,ACIDENTE,CONCEIÇÃO DAS ALAGOAS,MG,BRASIL,NaN,2012-01-08,16:00:00,0.0
...,...,...,...,...,...,...,...,...,...
5147,80446,ACIDENTE,JACAREACANGA,PA,BRASIL,NaN,2021-12-20,17:10:00,0.0
5151,80450,ACIDENTE,DOURADOS,MS,BRASIL,NaN,2021-12-28,10:30:00,0.0
5155,80455,INCIDENTE GRAVE,SANTA RITA,PB,BRASIL,NaN,2021-12-29,18:50:00,0.0
5158,80458,ACIDENTE,JATAÍ,GO,BRASIL,NaN,2021-12-30,20:30:00,0.0
5159,80452,ACIDENTE,MARACAÍ,SP,BRASIL,NaN,2021-12-31,09:30:00,0.0

In [58]:
#ocorrencias com mais de 10 recomendaçoes
filtro = df.total_recomendacoes > 10
df.loc[filtro]

,codigo_ocorrencia,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
844,47938,INCIDENTE,BRASÍLIA,DF,BRASIL,SBBR,2013-04-13,18:00:00,11.0
1669,52265,ACIDENTE,SANTOS,SP,BRASIL,NaN,2014-08-13,13:03:00,13.0
2804,66432,INCIDENTE GRAVE,VITÓRIA,ES,BRASIL,NaN,2017-02-21,11:47:00,12.0

In [62]:
#ocorrencias com mais de 10 recomendaçoes
filtro = df.total_recomendacoes > 10
df.loc[filtro, ['ocorrencia_cidade', 'total_recomendacoes']]

     ocorrencia_cidade  total_recomendacoes
844           BRASÍLIA                 11.0
1669            SANTOS                 13.0
2804           VITÓRIA                 12.0

In [64]:
#ocorrencias cuja classificação == INCIDENTE GRAVE
filtro = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
df.loc[filtro]

,codigo_ocorrencia,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
6,50713,INCIDENTE GRAVE,CAMPINAS,SP,BRASIL,SDAI,2012-01-07,18:15:00,0.0
12,45396,INCIDENTE GRAVE,MARABÁ,PA,BRASIL,SBMA,2012-01-11,11:21:00,0.0
18,50714,INCIDENTE GRAVE,CAMOCIM,CE,BRASIL,SNWC,2012-01-17,18:25:00,0.0
19,45399,INCIDENTE GRAVE,MUANÁ,PA,BRASIL,NaN,2012-01-18,17:35:00,0.0
24,45582,INCIDENTE GRAVE,RONDONÓPOLIS,MT,BRASIL,SWRD,2012-01-20,17:00:00,0.0
...,...,...,...,...,...,...,...,...,...
5135,80427,INCIDENTE GRAVE,NOVA BANDEIRANTES,MT,BRASIL,NaN,2021-12-12,17:20:00,0.0
5142,80448,INCIDENTE GRAVE,FORMOSO DO ARAGUAIA,TO,BRASIL,NaN,2021-12-18,19:00:00,0.0
5154,80454,INCIDENTE GRAVE,ARAÇATUBA,SP,BRASIL,SBAU,2021-12-29,21:35:00,0.0
5155,80455,INCIDENTE GRAVE,SANTA RITA,PB,BRASIL,NaN,2021-12-29,18:50:00,0.0
5160,80457,INCIDENTE GRAVE,NOVO HAMBURGO,RS,BRASIL,SSNH,2021-12-31,11:59:00,0.0

In [66]:
#ocorrencias cuja classificacao == INCIDENTE GRAVE e o estado == CE
filtro1 = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
filtro2 = df.ocorrencia_uf == 'CE'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
6,50713,INCIDENTE GRAVE,CAMPINAS,SP,BRASIL,SDAI,2012-01-07,18:15:00,0.0
12,45396,INCIDENTE GRAVE,MARABÁ,PA,BRASIL,SBMA,2012-01-11,11:21:00,0.0
18,50714,INCIDENTE GRAVE,CAMOCIM,CE,BRASIL,SNWC,2012-01-17,18:25:00,0.0
19,45399,INCIDENTE GRAVE,MUANÁ,PA,BRASIL,NaN,2012-01-18,17:35:00,0.0
24,45582,INCIDENTE GRAVE,RONDONÓPOLIS,MT,BRASIL,SWRD,2012-01-20,17:00:00,0.0
...,...,...,...,...,...,...,...,...,...
5135,80427,INCIDENTE GRAVE,NOVA BANDEIRANTES,MT,BRASIL,NaN,2021-12-12,17:20:00,0.0
5142,80448,INCIDENTE GRAVE,FORMOSO DO ARAGUAIA,TO,BRASIL,NaN,2021-12-18,19:00:00,0.0
5154,80454,INCIDENTE GRAVE,ARAÇATUBA,SP,BRASIL,SBAU,2021-12-29,21:35:00,0.0
5155,80455,INCIDENTE GRAVE,SANTA RITA,PB,BRASIL,NaN,2021-12-29,18:50:00,0.0
5160,80457,INCIDENTE GRAVE,NOVO HAMBURGO,RS,BRASIL,SSNH,2021-12-31,11:59:00,0.0

In [67]:
#ocorrencias cuja classificacao == INCIDENTE GRAVE ou o estado == CE
filtro1 = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
filtro2 = df.ocorrencia_uf == 'CE'
df.loc[filtro1 | filtro2]

,codigo_ocorrencia,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
6,50713,INCIDENTE GRAVE,CAMPINAS,SP,BRASIL,SDAI,2012-01-07,18:15:00,0.0
12,45396,INCIDENTE GRAVE,MARABÁ,PA,BRASIL,SBMA,2012-01-11,11:21:00,0.0
18,50714,INCIDENTE GRAVE,CAMOCIM,CE,BRASIL,SNWC,2012-01-17,18:25:00,0.0
19,45399,INCIDENTE GRAVE,MUANÁ,PA,BRASIL,NaN,2012-01-18,17:35:00,0.0
24,45582,INCIDENTE GRAVE,RONDONÓPOLIS,MT,BRASIL,SWRD,2012-01-20,17:00:00,0.0
...,...,...,...,...,...,...,...,...,...
5135,80427,INCIDENTE GRAVE,NOVA BANDEIRANTES,MT,BRASIL,NaN,2021-12-12,17:20:00,0.0
5142,80448,INCIDENTE GRAVE,FORMOSO DO ARAGUAIA,TO,BRASIL,NaN,2021-12-18,19:00:00,0.0
5154,80454,INCIDENTE GRAVE,ARAÇATUBA,SP,BRASIL,SBAU,2021-12-29,21:35:00,0.0
5155,80455,INCIDENTE GRAVE,SANTA RITA,PB,BRASIL,NaN,2021-12-29,18:50:00,0.0
5160,80457,INCIDENTE GRAVE,NOVO HAMBURGO,RS,BRASIL,SSNH,2021-12-31,11:59:00,0.0

In [68]:
#ocorrencias cuja (classificacao == INCIDENTE GRAVE ou classificacao == INCIDENTE) e o estado == SP
filtro1 = (df.ocorrencia_classificacao == 'INCIDENTE GRAVE') | (df.ocorrencia_classificacao == 'INCIDENTE')
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
5,52243,INCIDENTE,UBATUBA,SP,BRASIL,NaN,2012-01-06,14:30:00,0.0
6,50713,INCIDENTE GRAVE,CAMPINAS,SP,BRASIL,SDAI,2012-01-07,18:15:00,0.0
28,52248,INCIDENTE,SÃO PAULO,SP,BRASIL,SBMT,2012-01-21,11:15:00,0.0
35,52054,INCIDENTE,SÃO PAULO,SP,BRASIL,SBMT,2012-01-25,23:00:00,0.0
36,52055,INCIDENTE,RIBEIRÃO PRETO,SP,BRASIL,NaN,2012-01-25,09:30:00,0.0
...,...,...,...,...,...,...,...,...,...
5130,80425,INCIDENTE,SÃO PAULO,SP,BRASIL,SBSP,2021-12-09,20:30:00,0.0
5139,80431,INCIDENTE,SANTOS,SP,BRASIL,SBST,2021-12-15,12:30:00,0.0
5153,80453,INCIDENTE,CAMPINAS,SP,BRASIL,SBKP,2021-12-29,09:00:00,0.0
5154,80454,INCIDENTE GRAVE,ARAÇATUBA,SP,BRASIL,SBAU,2021-12-29,21:35:00,0.0
5157,80456,INCIDENTE,SÃO PAULO,SP,BRASIL,SBSP,2021-12-30,13:15:00,0.0

In [69]:
#ocorrencias cuja (classificacao == INCIDENTE GRAVE ou classificacao == INCIDENTE) e o estado == SP
# metodo isin
filtro1 = df.ocorrencia_classificacao.isin(['INCIDENTE GRAVE', 'INCIDENTE'])
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
5,52243,INCIDENTE,UBATUBA,SP,BRASIL,NaN,2012-01-06,14:30:00,0.0
6,50713,INCIDENTE GRAVE,CAMPINAS,SP,BRASIL,SDAI,2012-01-07,18:15:00,0.0
28,52248,INCIDENTE,SÃO PAULO,SP,BRASIL,SBMT,2012-01-21,11:15:00,0.0
35,52054,INCIDENTE,SÃO PAULO,SP,BRASIL,SBMT,2012-01-25,23:00:00,0.0
36,52055,INCIDENTE,RIBEIRÃO PRETO,SP,BRASIL,NaN,2012-01-25,09:30:00,0.0
...,...,...,...,...,...,...,...,...,...
5130,80425,INCIDENTE,SÃO PAULO,SP,BRASIL,SBSP,2021-12-09,20:30:00,0.0
5139,80431,INCIDENTE,SANTOS,SP,BRASIL,SBST,2021-12-15,12:30:00,0.0
5153,80453,INCIDENTE,CAMPINAS,SP,BRASIL,SBKP,2021-12-29,09:00:00,0.0
5154,80454,INCIDENTE GRAVE,ARAÇATUBA,SP,BRASIL,SBAU,2021-12-29,21:35:00,0.0
5157,80456,INCIDENTE,SÃO PAULO,SP,BRASIL,SBSP,2021-12-30,13:15:00,0.0

In [14]:
#ocorrencias do ano de 2015 e mês 01
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 1
filtro3 = df.ocorrencia_dia.dt.day == 27
df.loc[filtro1 & filtro2 & filtro3]

,codigo_ocorrencia,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
1907,52993,INCIDENTE GRAVE,CAMPOS DOS GOYTACAZES,RJ,BRASIL,SBFS,2015-01-27,12:25:00,0.0

In [23]:
df.dtypes

codigo_ocorrencia                    int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_pais                     object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                float64
ocorrencia_dia_hora                 object
dtype: object

In [16]:
#ocorrencias do ano de 2015 e mês 12 e dias entre 3 e 8
filtro_ano = df.ocorrencia_dia.dt.year == 2015
filtro_mes = df.ocorrencia_dia.dt.month == 12
filtro_diaini = df.ocorrencia_dia.dt.day > 2
filtro_diasfim = df.ocorrencia_dia.dt.day < 9
df.loc[filtro_ano & filtro_mes & filtro_diaini & filtro_diasfim]

,codigo_ocorrencia,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2306,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,BRASIL,SBFS,2015-12-03,10:50:00,0.0
2307,60637,INCIDENTE,BELO HORIZONTE,MG,BRASIL,SBBH,2015-12-03,16:47:00,0.0
2308,53625,ACIDENTE,TRINDADE,GO,BRASIL,NaN,2015-12-06,13:10:00,3.0
2309,53626,ACIDENTE,AMERICANA,SP,BRASIL,SDAI,2015-12-06,15:00:00,1.0
2310,53628,ACIDENTE,AGUAÍ,SP,BRASIL,NaN,2015-12-08,14:30:00,1.0
2311,53629,INCIDENTE GRAVE,JALES,SP,BRASIL,SDJL,2015-12-08,10:20:00,0.0
2312,53631,INCIDENTE,CAMPINAS,SP,BRASIL,SBKP,2015-12-08,16:19:00,0.0
2313,60636,INCIDENTE,CAXIAS DO SUL,RS,BRASIL,SBCX,2015-12-08,13:00:00,0.0

In [36]:
df['ocorrencia_dia_hora'] = pd.to_datetime(df.ocorrencia_dia.astype(str) + ' ' +  df.ocorrencia_hora)

In [38]:
schema.validate(df)

,codigo_ocorrencia,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
0,52242,INCIDENTE,PORTO ALEGRE,RS,BRASIL,SBPA,2012-01-05,20:27:00,0.0,2012-01-05 20:27:00
1,45331,ACIDENTE,GUARULHOS,SP,BRASIL,SBGR,2012-01-06,13:44:00,3.0,2012-01-06 13:44:00
2,45333,ACIDENTE,VIAMÃO,RS,BRASIL,NaN,2012-01-06,13:00:00,0.0,2012-01-06 13:00:00
3,45401,ACIDENTE,SÃO SEBASTIÃO,SP,BRASIL,NaN,2012-01-06,17:00:00,0.0,2012-01-06 17:00:00
4,45407,ACIDENTE,SÃO SEPÉ,RS,BRASIL,NaN,2012-01-06,16:30:00,0.0,2012-01-06 16:30:00
...,...,...,...,...,...,...,...,...,...,...
5158,80458,ACIDENTE,JATAÍ,GO,BRASIL,NaN,2021-12-30,20:30:00,0.0,2021-12-30 20:30:00
5159,80452,ACIDENTE,MARACAÍ,SP,BRASIL,NaN,2021-12-31,09:30:00,0.0,2021-12-31 09:30:00
5160,80457,INCIDENTE GRAVE,NOVO HAMBURGO,RS,BRASIL,SSNH,2021-12-31,11:59:00,0.0,2021-12-31 11:59:00
5161,80460,INCIDENTE,CURITIBA,PR,BRASIL,SBBI,2021-12-31,15:12:00,0.0,2021-12-31 15:12:00
5162,80467,INCIDENTE,PETROLINA,PE,BRASIL,SBPL,2021-12-31,20:30:00,0.0,2021-12-31 20:30:00

In [39]:
df.dtypes

codigo_ocorrencia                    int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_pais                     object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                float64
ocorrencia_dia_hora         datetime64[ns]
dtype: object

In [40]:
#ocorrencias do ano de 2015 e mês 12 e dias entre 3 e 8
filtro_ano = df.ocorrencia_dia_hora.dt.year == 2015
filtro_mes = df.ocorrencia_dia_hora.dt.month == 12
filtro_diaini = df.ocorrencia_dia_hora.dt.day > 2
filtro_diasfim = df.ocorrencia_dia_hora.dt.day < 9
df.loc[filtro_ano & filtro_mes & filtro_diaini & filtro_diasfim]

,codigo_ocorrencia,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
2306,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,BRASIL,SBFS,2015-12-03,10:50:00,0.0,2015-12-03 10:50:00
2307,60637,INCIDENTE,BELO HORIZONTE,MG,BRASIL,SBBH,2015-12-03,16:47:00,0.0,2015-12-03 16:47:00
2308,53625,ACIDENTE,TRINDADE,GO,BRASIL,NaN,2015-12-06,13:10:00,3.0,2015-12-06 13:10:00
2309,53626,ACIDENTE,AMERICANA,SP,BRASIL,SDAI,2015-12-06,15:00:00,1.0,2015-12-06 15:00:00
2310,53628,ACIDENTE,AGUAÍ,SP,BRASIL,NaN,2015-12-08,14:30:00,1.0,2015-12-08 14:30:00
2311,53629,INCIDENTE GRAVE,JALES,SP,BRASIL,SDJL,2015-12-08,10:20:00,0.0,2015-12-08 10:20:00
2312,53631,INCIDENTE,CAMPINAS,SP,BRASIL,SBKP,2015-12-08,16:19:00,0.0,2015-12-08 16:19:00
2313,60636,INCIDENTE,CAXIAS DO SUL,RS,BRASIL,SBCX,2015-12-08,13:00:00,0.0,2015-12-08 13:00:00

In [45]:
#exibindo por hora e dias especificos
filtro1 = df.ocorrencia_dia_hora >= '2015-12-03 11:00:00'
filtro2 = df.ocorrencia_dia_hora <= '2015-12-08 16:00:00'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
2307,60637,INCIDENTE,BELO HORIZONTE,MG,BRASIL,SBBH,2015-12-03,16:47:00,0.0,2015-12-03 16:47:00
2308,53625,ACIDENTE,TRINDADE,GO,BRASIL,NaN,2015-12-06,13:10:00,3.0,2015-12-06 13:10:00
2309,53626,ACIDENTE,AMERICANA,SP,BRASIL,SDAI,2015-12-06,15:00:00,1.0,2015-12-06 15:00:00
2310,53628,ACIDENTE,AGUAÍ,SP,BRASIL,NaN,2015-12-08,14:30:00,1.0,2015-12-08 14:30:00
2311,53629,INCIDENTE GRAVE,JALES,SP,BRASIL,SDJL,2015-12-08,10:20:00,0.0,2015-12-08 10:20:00
2313,60636,INCIDENTE,CAXIAS DO SUL,RS,BRASIL,SBCX,2015-12-08,13:00:00,0.0,2015-12-08 13:00:00

In [48]:
#agrupamento de dados para gerar novas informações
#ocorrencias do ano de 2015 e mes 03
filtro1 =  df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 3
#atribuindo em um novo dataframe
df201503 = df.loc[filtro1 & filtro2]
df201503

,codigo_ocorrencia,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
1960,53183,ACIDENTE,AMAPORÃ,PR,BRASIL,NaN,2015-03-02,23:00:00,0.0,2015-03-02 23:00:00
1961,53120,ACIDENTE,CHAVES,PA,BRASIL,SNXW,2015-03-04,13:30:00,0.0,2015-03-04 13:30:00
1962,53109,ACIDENTE,CAMPO GRANDE,MS,BRASIL,SSIE,2015-03-05,13:50:00,0.0,2015-03-05 13:50:00
1963,53112,ACIDENTE,MOGI GUAÇU,SP,BRASIL,NaN,2015-03-06,21:00:00,1.0,2015-03-06 21:00:00
1964,53152,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,BRASIL,SBRJ,2015-03-10,11:30:00,2.0,2015-03-10 11:30:00
1965,53167,INCIDENTE,MARABÁ,PA,BRASIL,SBMA,2015-03-10,17:33:00,0.0,2015-03-10 17:33:00
1966,53596,INCIDENTE,ITAPEMA,SC,BRASIL,NaN,2015-03-10,21:35:00,0.0,2015-03-10 21:35:00
1967,53149,ACIDENTE,TABATINGA,AM,BRASIL,SBTT,2015-03-11,23:25:00,0.0,2015-03-11 23:25:00
1968,53148,ACIDENTE,ARARAS,SP,BRASIL,SDEH,2015-03-12,12:40:00,0.0,2015-03-12 12:40:00
1969,53153,INCIDENTE,PORTO ALEGRE,RS,BRASIL,SBPA,2015-03-13,15:45:00,0.0,2015-03-13 15:45:00
1970,53154,INCIDENTE,SOROCABA,SP,BRASIL,SDCO,2015-03-13,14:40:00,0.0,2015-03-13 14:40:00
1971,53238,INCIDENTE,SERRA,ES,BRASIL,NaN,2015-03-13,11:30:00,0.0,2015-03-13 11:30:00
1972,53189,INCIDENTE,CONFINS,MG,BRASIL,SBCF,2015-03-14,07:20:00,0.0,2015-03-14 07:20:00
1973,53193,ACIDENTE,CANARANA,MT,BRASIL,NaN,2015-03-14,18:00:00,0.0,2015-03-14 18:00:00
1974,53164,ACIDENTE,PRINCESA ISABEL,PB,BRASIL,NaN,2015-03-15,18:30:00,0.0,2015-03-15 18:30:00
1975,53151,INCIDENTE GRAVE,MAUÉS,AM,BRASIL,SWMW,2015-03-16,18:07:00,1.0,2015-03-16 18:07:00
1976,53168,INCIDENTE,PARÁ DE MINAS,MG,BRASIL,SNPA,2015-03-16,21:05:00,0.0,2015-03-16 21:05:00
1977,53169,INCIDENTE,BELÉM,PA,BRASIL,SBBE,2015-03-19,03:25:00,0.0,2015-03-19 03:25:00
1978,53165,INCIDENTE GRAVE,SÃO DESIDÉRIO,BA,BRASIL,NaN,2015-03-20,14:35:00,0.0,2015-03-20 14:35:00
1979,53188,INCIDENTE,RIO DE JANEIRO,RJ,BRASIL,SBJR,2015-03-20,21:00:00,0.0,2015-03-20 21:00:00
1980,53184,ACIDENTE,PORTO UNIÃO,SC,BRASIL,NaN,2015-03-22,13:44:00,0.0,2015-03-22 13:44:00
1981,53178,ACIDENTE,DIAMANTINO,MT,BRASIL,NaN,2015-03-23,17:15:00,0.0,2015-03-23 17:15:00
1982,53182,ACIDENTE,SANTA LUZIA,MA,BRASIL,NaN,2015-03-23,20:40:00,0.0,2015-03-23 20:40:00
1983,53166,INCIDENTE GRAVE,RIACHÃO DAS NEVES,BA,BRASIL,NaN,2015-03-24,14:45:00,0.0,2015-03-24 14:45:00
1984,53170,INCIDENTE,CONFINS,MG,BRASIL,SBCF,2015-03-24,17:57:00,0.0,2015-03-24 17:57:00
1985,53185,INCIDENTE,CURITIBA,PR,BRASIL,SBCT,2015-03-24,23:01:00,0.0,2015-03-24 23:01:00
1986,53412,INCIDENTE GRAVE,MACAÉ,RJ,BRASIL,NaN,2015-03-24,16:35:00,0.0,2015-03-24 16:35:00
1987,53194,ACIDENTE,GUARACIABA DO NORTE,CE,BRASIL,SWBE,2015-03-26,20:30:00,0.0,2015-03-26 20:30:00
1988,53186,INCIDENTE,BRASÍLIA,DF,BRASIL,NaN,2015-03-27,14:55:00,0.0,2015-03-27 14:55:00
1989,53179,ACIDENTE,CAIAPÔNIA,GO,BRASIL,NaN,2015-03-28,10:30:00,0.0,2015-03-28 10:30:00
1990,53180,ACIDENTE,ARAGUARI,MG,BRASIL,NaN,2015-03-28,18:52:00,0.0,2015-03-28 18:52:00
1991,53190,INCIDENTE,CAMPINAS,SP,BRASIL,SBKP,2015-03-28,16:26:00,0.0,2015-03-28 16:26:00
1992,53212,INCIDENTE,JUNDIAÍ,SP,BRASIL,SBJD,2015-03-28,17:32:00,0.0,2015-03-28 17:32:00
1993,53213,INCIDENTE,JUNDIAÍ,SP,BRASIL,SBJD,2015-03-28,15:51:00,0.0,2015-03-28 15:51:00
1994,53181,ACIDENTE,COLÍDER,MT,BRASIL,NaN,2015-03-29,20:17:00,0.0,2015-03-29 20:17:00
1995,53187,INCIDENTE,JOINVILLE,SC,BRASIL,SBJV,2015-03-29,18:36:00,0.0,2015-03-29 18:36:00
1996,53211,INCIDENTE,BAURU,SP,BRASIL,SBBU,2015-03-30,19:40:00,0.0,2015-03-30 19:40:00

In [49]:
#ver o count para garantir os dados da coluna
df201503.count()

codigo_ocorrencia           37
ocorrencia_classificacao    37
ocorrencia_cidade           37
ocorrencia_uf               37
ocorrencia_pais             37
ocorrencia_aerodromo        21
ocorrencia_dia              37
ocorrencia_hora             37
total_recomendacoes         37
ocorrencia_dia_hora         37
dtype: int64

In [52]:
#agrupando e contando
df201503.groupby(['ocorrencia_classificacao']).ocorrencia_cidade.count()

ocorrencia_classificacao
ACIDENTE           15
INCIDENTE          17
INCIDENTE GRAVE     5
Name: ocorrencia_cidade, dtype: int64

In [53]:
#para nao cair nos nulos, usar o size()
df201503.groupby(['ocorrencia_classificacao']).size()

ocorrencia_classificacao
ACIDENTE           15
INCIDENTE          17
INCIDENTE GRAVE     5
dtype: int64

In [54]:
#agrupando por ordem crescente ou decrescente
df201503.groupby(['ocorrencia_classificacao']).size().sort_values(ascending=False)

ocorrencia_classificacao
INCIDENTE          17
ACIDENTE           15
INCIDENTE GRAVE     5
dtype: int64

In [58]:
#agrupamentos dos dados de uma regiao especifica em um ano especifico
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_uf.isin(['SP', 'MG', 'ES', 'RJ'])
dfsudeste2015 = df.loc[filtro1 & filtro2]
dfsudeste2015

,codigo_ocorrencia,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
1873,53074,INCIDENTE,BELO HORIZONTE,MG,BRASIL,SBBH,2015-01-02,20:34:00,0.0,2015-01-02 20:34:00
1875,53075,INCIDENTE,JUNDIAÍ,SP,BRASIL,SBJD,2015-01-05,10:19:00,0.0,2015-01-05 10:19:00
1876,53076,INCIDENTE,BRAGANÇA PAULISTA,SP,BRASIL,NaN,2015-01-06,11:30:00,0.0,2015-01-06 11:30:00
1879,53072,INCIDENTE,BELO HORIZONTE,MG,BRASIL,SBBH,2015-01-08,21:13:00,0.0,2015-01-08 21:13:00
1880,52994,INCIDENTE,SÃO PAULO,SP,BRASIL,SBMT,2015-01-09,23:25:00,0.0,2015-01-09 23:25:00
...,...,...,...,...,...,...,...,...,...,...
2332,60602,INCIDENTE,RIBEIRÃO PRETO,SP,BRASIL,SBRP,2015-12-22,06:27:00,0.0,2015-12-22 06:27:00
2333,60615,INCIDENTE,SÃO PAULO,SP,BRASIL,SBMT,2015-12-22,13:07:00,0.0,2015-12-22 13:07:00
2335,60641,INCIDENTE,BELO HORIZONTE,MG,BRASIL,SBBH,2015-12-23,15:53:00,0.0,2015-12-23 15:53:00
2336,60632,INCIDENTE GRAVE,ITABERÁ,SP,BRASIL,NaN,2015-12-24,14:00:00,0.0,2015-12-24 14:00:00
2337,60600,INCIDENTE,GUARULHOS,SP,BRASIL,SBGR,2015-12-25,19:00:00,0.0,2015-12-25 19:00:00

In [59]:
dfsudeste2015.groupby(['ocorrencia_classificacao']).size()

ocorrencia_classificacao
ACIDENTE            60
INCIDENTE          128
INCIDENTE GRAVE     19
dtype: int64

In [60]:
dfsudeste2015.count()

codigo_ocorrencia           207
ocorrencia_classificacao    207
ocorrencia_cidade           207
ocorrencia_uf               207
ocorrencia_pais             207
ocorrencia_aerodromo        152
ocorrencia_dia              207
ocorrencia_hora             207
total_recomendacoes         207
ocorrencia_dia_hora         207
dtype: int64

In [62]:
#agrupando por cidade
dfsudeste2015.groupby(['ocorrencia_cidade']).size().sort_values(ascending=True)

ocorrencia_cidade
AFONSO CLÁUDIO     1
PIRACICABA         1
PINDORAMA          1
PATROCÍNIO         1
PARÁ DE MINAS      1
                  ..
GUARULHOS         10
JUNDIAÍ           14
BELO HORIZONTE    18
RIO DE JANEIRO    19
SÃO PAULO         25
Length: 86, dtype: int64

In [66]:
#somando por cidade
filtro = dfsudeste2015.ocorrencia_cidade == 'RIO DE JANEIRO'
dfsudeste2015.loc[filtro].total_recomendacoes.sum()

6.0

In [68]:
#agrupar dentro das cidades o total de recomendaçoes
filtro = dfsudeste2010.total_recomendacoes > 0
dfsudeste2015.loc[filtro].groupby(['ocorrencia_cidade']).total_recomendacoes.sum().sort_values()

ocorrencia_cidade
AGUAÍ                1.0
MOGI GUAÇU           1.0
MIRACATU             1.0
JUNDIAÍ              1.0
ITÁPOLIS             1.0
TIETÊ                1.0
ITAPIRA              1.0
VIÇOSA               1.0
CATANDUVA            1.0
CABECEIRA GRANDE     1.0
BRAGANÇA PAULISTA    1.0
AMERICANA            1.0
GUARATINGUETÁ        1.0
MACAÉ                2.0
OURO PRETO           2.0
PIRACICABA           2.0
ITARIRI              2.0
BELO HORIZONTE       4.0
CARAPICUÍBA          5.0
RIO DE JANEIRO       6.0
Name: total_recomendacoes, dtype: float64

In [71]:
#agrupando por cidade, mes e somando o total de recomendaçoes
dfsudeste2010.loc[filtro].groupby(['ocorrencia_cidade', dfsudeste2015.ocorrencia_dia.dt.month]).total_recomendacoes.sum()

ocorrencia_cidade  ocorrencia_dia
AGUAÍ              12                1.0
MOGI GUAÇU         3                 1.0
MIRACATU           11                1.0
JUNDIAÍ            11                1.0
TIETÊ              5                 1.0
ITAPIRA            2                 1.0
GUARATINGUETÁ      6                 1.0
ITÁPOLIS           12                1.0
CABECEIRA GRANDE   5                 1.0
BRAGANÇA PAULISTA  11                1.0
AMERICANA          12                1.0
CATANDUVA          4                 1.0
VIÇOSA             5                 1.0
ITARIRI            8                 2.0
MACAÉ              6                 2.0
OURO PRETO         6                 2.0
PIRACICABA         6                 2.0
RIO DE JANEIRO     3                 2.0
BELO HORIZONTE     8                 4.0
RIO DE JANEIRO     12                4.0
CARAPICUÍBA        4                 5.0
Name: total_recomendacoes, dtype: float64

In [74]:
filtro1 = dfsudeste2010.total_recomendacoes > 0
filtro2 = dfsudeste2010.ocorrencia_cidade == 'SÃO PAULO'
dfsudeste2010.loc[filtro1 & filtro2]

Empty DataFrame
Columns: [codigo_ocorrencia, ocorrencia_classificacao, ocorrencia_cidade, ocorrencia_uf, ocorrencia_pais, ocorrencia_aerodromo, ocorrencia_dia, ocorrencia_hora, total_recomendacoes, ocorrencia_dia_hora]
Index: []